// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SA.ClubDeLeones.Infrastructure.Persistencia;

#nullable disable

namespace SA.ClubDeLeones.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampanaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lugar")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId");

                    b.ToTable("Actividades", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.AyudaSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampanaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.HasIndex("CampanaId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("AyudasSociales", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Beneficiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SituacionNecesidad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Beneficiarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Campana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ObjetivoMonto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Campanas", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Donacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampanaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DonanteNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ReciboNumero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampanaId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Donaciones", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.ActividadBeneficiario", b =>
                {
                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Asistio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaAsistencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ActividadId", "BeneficiarioId");

                    b.HasIndex("BeneficiarioId");

                    b.ToTable("ActividadBeneficiarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.ActividadVoluntario", b =>
                {
                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaParticipacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("RolEnActividad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ActividadId", "VoluntarioId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("ActividadVoluntarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.CampanaBeneficiario", b =>
                {
                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeneficiarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("CampanaId", "BeneficiarioId");

                    b.HasIndex("BeneficiarioId");

                    b.ToTable("CampanaBeneficiarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.CampanaVoluntario", b =>
                {
                    b.Property<Guid>("CampanaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaParticipacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("RolEnCampana")
                        .HasColumnType("text");

                    b.HasKey("CampanaId", "VoluntarioId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("CampanaVoluntarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("VoluntarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("VoluntarioId")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Voluntario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Disponibilidad")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Voluntarios", (string)null);
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Actividad", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Campana", "Campana")
                        .WithMany("Actividades")
                        .HasForeignKey("CampanaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campana");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.AyudaSocial", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Beneficiario", "Beneficiario")
                        .WithMany("AyudasRecibidas")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Campana", "Campana")
                        .WithMany("AyudasGeneradas")
                        .HasForeignKey("CampanaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Voluntario", "Voluntario")
                        .WithMany("AyudasEntregadas")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Beneficiario");

                    b.Navigation("Campana");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Donacion", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Campana", "Campana")
                        .WithMany("Donaciones")
                        .HasForeignKey("CampanaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Voluntario", "Voluntario")
                        .WithMany("DonacionesRegistradas")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campana");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.ActividadBeneficiario", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Actividad", "Actividad")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Beneficiario", "Beneficiario")
                        .WithMany("Actividades")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Beneficiario");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.ActividadVoluntario", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Actividad", "Actividad")
                        .WithMany("Voluntarios")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Voluntario", "Voluntario")
                        .WithMany("Actividades")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.CampanaBeneficiario", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Beneficiario", "Beneficiario")
                        .WithMany("Campanas")
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Campana", "Campana")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("CampanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiario");

                    b.Navigation("Campana");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Relaciones.CampanaVoluntario", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Campana", "Campana")
                        .WithMany("Voluntarios")
                        .HasForeignKey("CampanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Voluntario", "Voluntario")
                        .WithMany("Campanas")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campana");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Usuario", b =>
                {
                    b.HasOne("SA.ClubDeLeones.Domain.Entidades.Voluntario", "Voluntario")
                        .WithOne("Usuario")
                        .HasForeignKey("SA.ClubDeLeones.Domain.Entidades.Usuario", "VoluntarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Actividad", b =>
                {
                    b.Navigation("Beneficiarios");

                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Beneficiario", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("AyudasRecibidas");

                    b.Navigation("Campanas");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Campana", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("AyudasGeneradas");

                    b.Navigation("Beneficiarios");

                    b.Navigation("Donaciones");

                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("SA.ClubDeLeones.Domain.Entidades.Voluntario", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("AyudasEntregadas");

                    b.Navigation("Campanas");

                    b.Navigation("DonacionesRegistradas");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
